### ISSUE TITLE
Descending default sort no longer works

### ISSUE THREAD

**Issue by footballencarta** [spatie/laravel-query-builder#178]
With the release of 1.14.0 - the ability to set default sorts to descending no longer works.

For example:

**1.13.2**

```
QueryBuilder::for(User::class)
            ->defaultSort('-name')
            ->get();
```

Results in: 

`select * from "users" order by "name" desc, "name" desc`

**1.14.0**

```
QueryBuilder::for(User::class)
            ->defaultSort('-name')
            ->get();
```
Results in: 

`select * from "users" order by "-name" desc, "-name" desc`

The value being passed into default sorts no longer seems to parse the descending modifier correctly.

**Comment by AlexVanderbist** [comment]
Thanks! The fix is merged and a version tagged 👍

**Comment by duongtdvn** [comment]
I have upgraded to the latest version 1.15.2 and the bug still remain 🙁.

**Comment by dominikb** [comment]
I'm unable to reproduce the original bug with not removing the leading dash (order by "-name" desc").

Are you actually referring to the order clause being added twice? This I can reproduce on 1.15.2 and I've already found the cause, but am still fiddling with a proper solution.
