### ISSUE TITLE
Appends do not work with pagination

### ISSUE THREAD

**Issue by PunyFlash** [spatie/laravel-query-builder#644]
I have such controller:

```php
public function index()
{
    return QueryBuilder::for(User::class)
        ->allowedFields(['first_name', 'last_name', 'username', 'photo_url', 'email', 'auth_date'])
        ->allowedAppends(['online'])
        ->allowedFilters('first_name', 'last_name', 'username', 'email', 'auth_date')
        ->allowedSorts('first_name', 'last_name', 'username', 'email', 'auth_date')
        ->cursorPaginate(10);
}
```

When retrieving query results using `paginate`, `cursorPaginate` and `simplePaginate` attributes are not being appended:

```json
// 20210704210622
// http://127.0.0.4/api/users?append=online

{
  "data": [
    {
      "id": 1,
      "telegram_id": null,
      "first_name": "Anibal",
      "last_name": "Dickinson",
      "username": "talon.hill",
      "photo_url": "https://picsum.photos/600/600",
      "email": "oleta.breitenberg@example.com",
      "email_verified_at": "2021-07-02T22:12:19.000000Z",
      "auth_date": null,
      "created_at": "2021-07-02T22:12:20.000000Z",
      "updated_at": "2021-07-02T22:12:20.000000Z"
    },
    {
      "id": 2,
      "telegram_id": null,
      "first_name": "Garret",
      "last_name": "Mueller",
      "username": "delphia86",
      "photo_url": "https://picsum.photos/600/600",
      "email": "kaya91@example.org",
      "email_verified_at": "2021-07-02T22:12:19.000000Z",
      "auth_date": null,
      "created_at": "2021-07-02T22:12:20.000000Z",
      "updated_at": "2021-07-02T22:12:20.000000Z"
    },
    {
      "id": 3,
      "telegram_id": null,
      "first_name": "Abdullah",
      "last_name": "Schuppe",
      "username": "slakin",
      "photo_url": "https://picsum.photos/600/600",
      "email": "dallas.keebler@example.com",
      "email_verified_at": "2021-07-02T22:12:19.000000Z",
      "auth_date": null,
      "created_at": "2021-07-02T22:12:20.000000Z",
      "updated_at": "2021-07-02T22:12:20.000000Z"
    },
    {
      "id": 4,
      "telegram_id": null,
      "first_name": "Alison",
      "last_name": "Halvorson",
      "username": "leanne37",
      "photo_url": "https://picsum.photos/600/600",
      "email": "panderson@example.org",
      "email_verified_at": "2021-07-02T22:12:19.000000Z",
      "auth_date": null,
      "created_at": "2021-07-02T22:12:20.000000Z",
      "updated_at": "2021-07-02T22:12:20.000000Z"
    },
    {
      "id": 5,
      "telegram_id": null,
      "first_name": "Cierra",
      "last_name": "Emmerich",
      "username": "sbahringer",
      "photo_url": "https://picsum.photos/600/600",
      "email": "easter.greenholt@example.org",
      "email_verified_at": "2021-07-02T22:12:19.000000Z",
      "auth_date": null,
      "created_at": "2021-07-02T22:12:21.000000Z",
      "updated_at": "2021-07-02T22:12:21.000000Z"
    },
    {
      "id": 6,
      "telegram_id": null,
      "first_name": "Bradley",
      "last_name": "Armstrong",
      "username": "dominique.wunsch",
      "photo_url": "https://picsum.photos/600/600",
      "email": "easter93@example.com",
      "email_verified_at": "2021-07-02T22:12:19.000000Z",
      "auth_date": null,
      "created_at": "2021-07-02T22:12:21.000000Z",
      "updated_at": "2021-07-02T22:12:21.000000Z"
    },
    {
      "id": 7,
      "telegram_id": null,
      "first_name": "Kiel",
      "last_name": "Jacobi",
      "username": "iohara",
      "photo_url": "https://picsum.photos/600/600",
      "email": "altenwerth.saul@example.net",
      "email_verified_at": "2021-07-02T22:12:20.000000Z",
      "auth_date": null,
      "created_at": "2021-07-02T22:12:21.000000Z",
      "updated_at": "2021-07-02T22:12:21.000000Z"
    },
    {
      "id": 8,
      "telegram_id": null,
      "first_name": "Kenton",
      "last_name": "Fadel",
      "username": "schuyler.trantow",
      "photo_url": "https://picsum.photos/600/600",
      "email": "fabiola50@example.com",
      "email_verified_at": "2021-07-02T22:12:20.000000Z",
      "auth_date": null,
      "created_at": "2021-07-02T22:12:21.000000Z",
      "updated_at": "2021-07-02T22:12:21.000000Z"
    },
    {
      "id": 9,
      "telegram_id": null,
      "first_name": "Natasha",
      "last_name": "Moore",
      "username": "corkery.celestine",
      "photo_url": "https://picsum.photos/600/600",
      "email": "walton10@example.com",
      "email_verified_at": "2021-07-02T22:12:20.000000Z",
      "auth_date": null,
      "created_at": "2021-07-02T22:12:21.000000Z",
      "updated_at": "2021-07-02T22:12:21.000000Z"
    },
    {
      "id": 10,
      "telegram_id": null,
      "first_name": "Candida",
      "last_name": "Berge",
      "username": "ericka.williamson",
      "photo_url": "https://picsum.photos/600/600",
      "email": "wehner.reilly@example.com",
      "email_verified_at": "2021-07-02T22:12:20.000000Z",
      "auth_date": null,
      "created_at": "2021-07-02T22:12:21.000000Z",
      "updated_at": "2021-07-02T22:12:21.000000Z"
    }
  ],
  "path": "http://127.0.0.4/api/users",
  "per_page": 10,
  "next_page_url": "http://127.0.0.4/api/users?cursor=eyJ1c2Vycy5pZCI6MTAsIl9wb2ludHNUb05leHRJdGVtcyI6dHJ1ZX0",
  "prev_page_url": null
}
```

**Comment by AlexVanderbist** [comment]
Thanks for letting us know. Fixed in v3.5.0

**Comment by nikitabuida** [comment]
> Thanks for letting us know. Fixed in v3.5.0

Using v4.0.2 and the issue is still here - not appending custom attributes via paginate().
